version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    build: .
#   runserver 0.0.0.0 from all interface access
#   runserver 127.0.0.1 from only localhost access    
    command: sh -c 'cd /code/test;python3 manage.py runserver 127.0.0.1:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
